import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import ads from "../src/data/monetization/ads.json" with { type: "json" };
import placements from "../src/data/monetization/placements.json" with { type: "json" };
import { readerBreaks } from "../src/monetization/placements.js";
const text = JSON.stringify(ads);
test("the enabled inventory uses the approved zones",()=>{assert.equal(ads.enabled,true);assert.ok(Object.values(ads.ads).every(ad=>ad.enabled));for(const [id,zone] of Object.entries({leaderboard_900x250:5865240,top_banner_728x90:5865232,banner_300x250:5865344,video_slider:5880066,desktop_interstitial:5880058,mobile_interstitial:5880060,popunder:5962682}))assert.match(ads.ads[id].snippet,new RegExp(String(zone)));assert.equal(text.includes("586" + "5392"), false);assert.equal(text.includes("INSERT THE COMPLETE"), false);assert.equal(text.includes("`".repeat(3)), false)});
test("every placement, global system, and verification are enabled and resolve",()=>{assert.equal(placements.enabled,true);assert.equal(placements.global.enabled,true);assert.deepEqual(placements.verification,{enabled:true,showPlacementLabels:true,showProviderState:true,showFallbackReason:true});for(const p of Object.values(placements.placements)){assert.equal(p.enabled,true);assert.equal(ads.ads[p.adId].enabled,true)}});
test("reader frequency is entirely configuration driven",()=>{assert.deepEqual(readerBreaks(10).map(x=>x.afterPage),[4,8]);const config=structuredClone(placements.placements.reader_between_pages);config.frequency.everyPages=3;assert.deepEqual(readerBreaks(10,config).map(x=>x.afterPage),[3,6,9])});
test("renderer preserves configured snippets without eval and provides fill detection",async()=>{const renderer=await readFile(new URL("../src/monetization/renderer.js",import.meta.url),"utf8");const loader=await readFile(new URL("../src/monetization/script-loader.js",import.meta.url),"utf8");assert.match(renderer,/createElement\("template"\)/);assert.match(loader,/source\.attributes/);assert.match(loader,/source\.textContent/);assert.doesNotMatch(renderer+loader,/\beval\s*\(|new Function/);assert.match(renderer,/MutationObserver/);assert.match(renderer,/ResizeObserver/);assert.match(renderer,/getBoundingClientRect/)});
test("fallback is black, branded, bounded, and interstitial failures collapse",async()=>{const [fallback,css,renderer]=await Promise.all(["fallback.js","styles/ad-slots.css","renderer.js"].map(file=>readFile(new URL(`../src/monetization/${file}`,import.meta.url),"utf8")));assert.match(fallback,/Doku-Doujins/);assert.match(css,/background:#000/);assert.match(css,/max-width:100%/);assert.match(renderer,/\["interstitial", "popunder"\].+collapse/)});
test("page integrations contain placement IDs but no provider details",async()=>{const files=await Promise.all(["main.js","page/landing.js","page/reader.js"].map(file=>readFile(new URL(`../src/${file}`,import.meta.url),"utf8")));assert.match(files[1],/landing_top_leaderboard/);assert.match(files[2],/reader_between_pages/);for(const source of files)assert.doesNotMatch(source,/magsrv|pemsrv|data-zoneid|eas6a/)});

test("Rotunda owns one complete centered row with no adjacent ad node",async()=>{const [landing,css]=await Promise.all([readFile(new URL("../src/page/landing.js",import.meta.url),"utf8"),readFile(new URL("../src/monetization/styles/ad-slots.css",import.meta.url),"utf8")]);const row=landing.match(/<section class="rotunda-layer landing-rotunda-frame"[\s\S]*?<\/section>/)?.[0]||"";assert.match(row,/data-rotunda-full-row="true"/);assert.equal((row.match(/<div/g)||[]).length,1);assert.doesNotMatch(row,/ad-|fallback|aside|verification/);assert.match(css,/\.landing-rotunda-frame\{display:flex;width:100%;justify-content:center;align-items:center/);assert.doesNotMatch(css,/landing-ad-rail|landing-rotunda-frame\{display:grid|landing-rotunda-frame[^}]*grid-template-columns/)});

test("fill detection policy is centralized and terminal",()=>{assert.deepEqual(placements.global.fillDetection,{timeoutMs:10000,claimedGracePeriodMs:5000,filledStateIsTerminal:true,acceptIframeAsFill:true,acceptProviderChildAsFill:true,acceptProviderMutationAsClaimed:true,fallbackOnlyWhenCompletelyEmpty:true,retryUntouchedOnce:false})});

test("renderer treats cross-origin iframe, provider children and replacement as fill",async()=>{const source=await readFile(new URL("../src/monetization/renderer.js",import.meta.url),"utf8");assert.match(source,/tagName === "IFRAME"/);assert.match(source,/providerChildren\.length/);assert.match(source,/!originalIns\.isConnected/);assert.doesNotMatch(source,/contentDocument|contentWindow/);assert.match(source,/if \(filled && next !== "filled"\) return/);assert.match(source,/clearTimers\(\); setState\("filled"\)/);assert.match(source,/const final = inspect\(\)/);assert.match(source,/dataset\.adVerificationUi/);assert.match(source,/dataset\.adFallback/)});

test("loader shares exact URLs but every placement retains a private serve lifecycle",async()=>{const [renderer,loader]=await Promise.all([readFile(new URL("../src/monetization/renderer.js",import.meta.url),"utf8"),readFile(new URL("../src/monetization/script-loader.js",import.meta.url),"utf8")]);assert.match(loader,/externalScripts\.has\(url\)/);assert.match(loader,/script\.src === url/);assert.match(renderer,/document\.createElement\("div"\)/);assert.match(renderer,/source\.cloneNode\(true\)/);assert.match(renderer,/originalIns && !originalIns\.isConnected/);assert.match(renderer,/for \(const source of inline\) host\.appendChild\(copyScript\(source\)\)/);assert.equal((ads.ads.leaderboard_900x250.snippet.match(/data-zoneid="5865240"/g)||[]).length,1);assert.equal((ads.ads.top_banner_728x90.snippet.match(/data-zoneid="5865232"/g)||[]).length,1);assert.notEqual(new URL("https://a.magsrv.com/ad-provider.js").href,new URL("https://a.pemsrv.com/ad-provider.js").href)});
